language: ruby
before_install: gem install bundler
rvm:
  - 2.7
  - 2.6
  - 2.5
gemfile:
  - gemfiles/6.0.gemfile
  - gemfiles/5.2.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.0.gemfile

cache: bundler
